services:
  - type: web
    name: lehi-load-forecast
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATA_CSV_URL
        value: https://raw.githubusercontent.com/crobinson111/lehi-load-forecast/master/data/load_history.csv
      - key: RED_MESA_CSV_URL
        value: https://raw.githubusercontent.com/crobinson111/lehi-load-forecast/master/data/red_mesa_history.csv
