services:
  - type: web
    name: lehi-load-forecast
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATA_CSV_URL
        value: https://raw.githubusercontent.com/crobinson111/lehi-load-forecast/master/data/load_history.csv
      - key: RED_MESA_CSV_URL
        value: https://raw.githubusercontent.com/crobinson111/lehi-load-forecast/master/data/red_mesa_history.csv
      - key: STEELE_A_CSV_URL
        value: https://raw.githubusercontent.com/crobinson111/lehi-load-forecast/master/data/steele_a_history.csv
      - key: LOAD_WEATHER_CSV_URL
        value: https://raw.githubusercontent.com/crobinson111/lehi-load-forecast/master/data/load_weather.csv
      - key: SOLAR_WEATHER_CSV_URL
        value: https://raw.githubusercontent.com/crobinson111/lehi-load-forecast/master/data/solar_weather.csv
      - key: STEELE_A_WEATHER_CSV_URL
        value: https://raw.githubusercontent.com/crobinson111/lehi-load-forecast/master/data/steele_a_weather.csv
      - key: SUPPLY_HISTORY_CSV_URL
        value: https://raw.githubusercontent.com/crobinson111/lehi-load-forecast/master/data/supply_history.csv
      - key: H_BUTTE_WEATHER_CSV_URL
        value: https://raw.githubusercontent.com/crobinson111/lehi-load-forecast/master/data/h_butte_weather.csv
      - key: UAMPS_SCHEDULE_CSV_URL
        value: https://raw.githubusercontent.com/crobinson111/lehi-load-forecast/master/data/uamps_schedule.csv
