services:
  - type: web
    name: lehi-load-forecast
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: TENANT_ID
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: CLIENT_SECRET
        sync: false
      - key: SHAREPOINT_HOST
        sync: false
      - key: SHAREPOINT_SITE_PATH
        sync: false
      - key: SHAREPOINT_FILE_PATH
        sync: false
      - key: SHEET_NAME
        value: Sheet1
